<?php

namespace ContainerTHmqF9l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MessageType' shared autowired service.
     *
     * @return \App\Form\MessageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MessageType.php';

        return $container->privates['App\\Form\\MessageType'] = new \App\Form\MessageType();
    }
}
