<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xjY3J1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xjY3J1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4xjY3J1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4xjY3J1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4xjY3J1\App_KernelDevDebugContainer([
    'container.build_hash' => '4xjY3J1',
    'container.build_id' => 'f79aff92',
    'container.build_time' => 1638455144,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xjY3J1');
