<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVBviK5m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVBviK5m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVBviK5m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVBviK5m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVBviK5m\App_KernelDevDebugContainer([
    'container.build_hash' => 'VBviK5m',
    'container.build_id' => '154e6c24',
    'container.build_time' => 1637852905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVBviK5m');
