<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKDlaxsO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKDlaxsO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKDlaxsO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKDlaxsO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKDlaxsO\App_KernelDevDebugContainer([
    'container.build_hash' => 'KDlaxsO',
    'container.build_id' => '6b617df7',
    'container.build_time' => 1638452023,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKDlaxsO');
